version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: "./back-end"
    # depends_on:
    #   - mysql_db
    volumes:
      - /app/node_modules
      - ./back-end:/app
    # environment:
    #   <<: *common-variables
    #   MYSQL_HOST_IP: mysql_db

  client:
    # stdin_open: true
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./todo
    volumes:
      - /app/node_modules
      - ./todo:/app
